# Generated by Django 3.0.1 on 2019-12-26 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Register',
        ),
    ]
