# Generated by Django 3.0.1 on 2019-12-27 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20191227_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='User',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
