# Generated by Django 3.0.1 on 2019-12-30 11:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0013_auto_20191230_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 30, 17, 8, 0, 648183)),
        ),
    ]
